export const MOVIES_LIST_REQUEST  = 'MOVIES_LIST_REQUEST';
export const MOVIES_LIST_SUCCESS  = 'MOVIES_LIST_SUCCESS';
export const MOVIES_LIST_FAIL     = 'MOVIES_LIST_FAIL';

export const MOVIES_DETAILS_REQUEST  = 'MOVIES_DETAILS_REQUEST';
export const MOVIES_DETAILS_SUCCESS  = 'MOVIES_DETAILS_SUCCESS';
export const MOVIES_DETAILS_FAIL     = 'MOVIES_DETAILS_FAIL';

export const SEARCH_MOVIE_REQUEST  = 'SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_SUCCESS  = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAIL     = 'SEARCH_MOVIE_FAIL';

export const ADD_MOVIE_FAVORITE_REQUEST = 'ADD_MOVIE_FAVORITE_REQUEST';
export const ADD_MOVIE_FAVORITE_SUCCESS = 'ADD_MOVIE_FAVORITE_SUCCESS';
export const ADD_MOVIE_FAVORITE_FAIL = 'ADD_MOVIE_FAVORITE_FAIL';

export const LIST_MOVIE_FAVORITE_REQUEST = 'LIST_MOVIE_FAVORITE_REQUEST';
export const LIST_MOVIE_FAVORITE_SUCCESS = 'LIST_MOVIE_FAVORITE_SUCCESS';
export const LIST_MOVIE_FAVORITE_FAIL =    'LIST_MOVIE_FAVORITE_FAIL';

export const REMOVE_MOVIE_FAVORITE_REQUEST = 'REMOVE_MOVIE_FAVORITE_REQUEST';
export const REMOVE_MOVIE_FAVORITE_SUCCESS = 'REMOVE_MOVIE_FAVORITE_SUCCESS';
export const REMOVE_MOVIE_FAVORITE_FAIL = 'REMOVE_MOVIE_FAVORITE_FAIL';

export const GENDER_LIST_REQUEST  = 'GENDER_LIST_REQUEST';
export const GENDER_LIST_SUCCESS  = 'GENDER_LIST_SUCCESS';
export const GENDER_LIST_FAIL     = 'GENDER_LIST_FAIL';


